module.exports = {
    "preset": "ts-jest",
    "moduleFileExtensions": ["js", "jsx", "ts", "tsx", "vue"],
    "transform": {
        "^.+\\.vue$": "@vue/vue3-jest",
        "^.+\\.(js|jsx)?$": "babel-jest"
    },
    "testEnvironment": "jsdom",
    "setupFilesAfterEnv": ["jest-extended"],
    "globals": {"ts-jest": {"tsconfig": "./tsconfig.test.json"}},
    "moduleNameMapper": {
        "@banquette/api$": "<rootDir>/packages/api/src/index.ts",
        "@banquette/config$": "<rootDir>/packages/config/src/index.ts",
        "@banquette/dependency-injection$": "<rootDir>/packages/dependency-injection/src/index.ts",
        "@banquette/dom-modules$": "<rootDir>/packages/dom-modules/src/index.ts",
        "@banquette/event$": "<rootDir>/packages/event/src/index.ts",
        "@banquette/exception$": "<rootDir>/packages/exception/src/index.ts",
        "@banquette/fingerprint$": "<rootDir>/packages/fingerprint/src/index.ts",
        "@banquette/form$": "<rootDir>/packages/form/src/index.ts",
        "@banquette/http$": "<rootDir>/packages/http/src/index.ts",
        "@banquette/inversify$": "<rootDir>/packages/inversify/src/index.ts",
        "@banquette/log$": "<rootDir>/packages/log/src/index.ts",
        "@banquette/model$": "<rootDir>/packages/model/src/index.ts",
        "@banquette/model-api$": "<rootDir>/packages/model-api/src/index.ts",
        "@banquette/model-form$": "<rootDir>/packages/model-form/src/index.ts",
        "@banquette/model-validation$": "<rootDir>/packages/model-validation/src/index.ts",
        "@banquette/promise$": "<rootDir>/packages/promise/src/index.ts",
        "@banquette/storage$": "<rootDir>/packages/storage/src/index.ts",
        "@banquette/utils-array/(.*)$": "<rootDir>/packages/utils-array/src/$1",
        "@banquette/utils-crypto/(.*)$": "<rootDir>/packages/utils-crypto/src/$1",
        "@banquette/utils-date/(.*)$": "<rootDir>/packages/utils-date/src/$1",
        "@banquette/utils-dom/(.*)$": "<rootDir>/packages/utils-dom/src/$1",
        "@banquette/utils-easing/(.*)$": "<rootDir>/packages/utils-easing/src/$1",
        "@banquette/utils-glob$": "<rootDir>/packages/utils-glob/src/index.ts",
        "@banquette/utils-misc/(.*)$": "<rootDir>/packages/utils-misc/src/$1",
        "@banquette/utils-object/(.*)$": "<rootDir>/packages/utils-object/src/$1",
        "@banquette/utils-random/(.*)$": "<rootDir>/packages/utils-random/src/$1",
        "@banquette/utils-reflection/(.*)$": "<rootDir>/packages/utils-reflection/src/$1",
        "@banquette/utils-string/(.*)$": "<rootDir>/packages/utils-string/src/$1",
        "@banquette/utils-type/(.*)$": "<rootDir>/packages/utils-type/src/$1",
        "@banquette/validation$": "<rootDir>/packages/validation/src/index.ts",
        "@banquette/vue-dom-module$": "<rootDir>/packages/vue-dom-module/src/index.ts",
        "@banquette/vue-material-icons$": "<rootDir>/packages/vue-material-icons/src/index.ts",
        "@banquette/vue-typescript$": "<rootDir>/packages/vue-typescript/src/index.ts"
    },
    "modulePathIgnorePatterns": [
        "__mocks__",
        "unused-packages",
        "^(?!.*\\.test\\.(?:t|j)s$).+$"
    ],
    "unmockedModulePathPatterns": ["<rootDir>/node_modules/"]
}
