module.exports = {
    "preset": "ts-jest",
    "moduleFileExtensions": ["js", "jsx", "ts", "tsx", "vue"],
    "transform": {
        "^.+\\.vue$": "@vue/vue3-jest",
        "^.+\\.(js|jsx)?$": "babel-jest"
    },
    "testEnvironment": "jsdom",
    "setupFilesAfterEnv": ["jest-extended"],
    "globals": {"ts-jest": {"tsconfig": "./tsconfig.test.json"}},
    "moduleNameMapper": {
        "@banquette/api$": "<rootDir>/packages/api/src/index.ts",
        "@banquette/config$": "<rootDir>/packages/config/src/index.ts",
        "@banquette/dependency-injection$": "<rootDir>/packages/dependency-injection/src/index.ts",
        "@banquette/dom-modules$": "<rootDir>/packages/dom-modules/src/index.ts",
        "@banquette/event$": "<rootDir>/packages/event/src/index.ts",
        "@banquette/exception$": "<rootDir>/packages/exception/src/index.ts",
        "@banquette/fingerprint$": "<rootDir>/packages/fingerprint/src/index.ts",
        "@banquette/form$": "<rootDir>/packages/form/src/index.ts",
        "@banquette/http$": "<rootDir>/packages/http/src/index.ts",
        "@banquette/inversify$": "<rootDir>/packages/inversify/src/index.ts",
        "@banquette/log$": "<rootDir>/packages/log/src/index.ts",
        "@banquette/promise$": "<rootDir>/packages/promise/src/index.ts",
        "@banquette/storage$": "<rootDir>/packages/storage/src/index.ts",
        "@banquette/utils-array$": "<rootDir>/packages/utils-array/src/index.ts",
        "@banquette/utils-base64$": "<rootDir>/packages/utils-base64/src/index.ts",
        "@banquette/utils-color$": "<rootDir>/packages/utils-color/src/index.ts",
        "@banquette/utils-crypto$": "<rootDir>/packages/utils-crypto/src/index.ts",
        "@banquette/utils-date$": "<rootDir>/packages/utils-date/src/index.ts",
        "@banquette/utils-dom$": "<rootDir>/packages/utils-dom/src/index.ts",
        "@banquette/utils-easing$": "<rootDir>/packages/utils-easing/src/index.ts",
        "@banquette/utils-glob$": "<rootDir>/packages/utils-glob/src/index.ts",
        "@banquette/utils-json$": "<rootDir>/packages/utils-json/src/index.ts",
        "@banquette/utils-misc$": "<rootDir>/packages/utils-misc/src/index.ts",
        "@banquette/utils-object$": "<rootDir>/packages/utils-object/src/index.ts",
        "@banquette/utils-random$": "<rootDir>/packages/utils-random/src/index.ts",
        "@banquette/utils-reflection$": "<rootDir>/packages/utils-reflection/src/index.ts",
        "@banquette/utils-string$": "<rootDir>/packages/utils-string/src/index.ts",
        "@banquette/utils-type$": "<rootDir>/packages/utils-type/src/index.ts",
        "@banquette/validation$": "<rootDir>/packages/validation/src/index.ts",
        "@banquette/vue-dom-module$": "<rootDir>/packages/vue-dom-module/src/index.ts",
        "@banquette/vue-typescript$": "<rootDir>/packages/vue-typescript/src/index.ts"
    },
    "modulePathIgnorePatterns": [
        "__mocks__",
        "unused-packages",
        "^(?!.*\\.test\\.(?:t|j)s$).+$"
    ],
    "unmockedModulePathPatterns": ["<rootDir>/node_modules/"]
}
