<style src="./icon.component.css" scoped></style>
<script lang="ts">
import { isUndefined } from "@banquette/utils-type/is-undefined";
import { IconRemixQuestionMark } from "@banquette/vue-remix-icons/question-mark";
import { Component } from "@banquette/vue-typescript/decorator/component.decorator";
import { Computed } from "@banquette/vue-typescript/decorator/computed.decorator";
import { Prop } from "@banquette/vue-typescript/decorator/prop.decorator";
import { Render } from "@banquette/vue-typescript/decorator/render.decorator";
import { Themeable } from "@banquette/vue-typescript/decorator/themeable.decorator";
import { BindThemeDirective } from "@banquette/vue-typescript/theme/bind-theme.directive";
import { Vue } from "@banquette/vue-typescript/vue";
import {
    resolveDirective,
    withDirectives,
    openBlock,
    createBlock,
    resolveDynamicComponent,
    mergeProps,
    Directive, h
} from "vue";
import { ThemeConfiguration } from "./theme-configuration";

@Themeable(ThemeConfiguration)
@Component({
    name: 'bt-icon',
    components: [IconRemixQuestionMark],
    directives: [BindThemeDirective],
    inheritAttrs: false
})
export default class IconComponent extends Vue {
    /**
     * Elements' tags are stored by their index in this array to reduce the size of the data structure.
     * Only used if icons are added via the `icons` prop.
     */
    private static TagsMap = ['g', 'path', 'polygon', 'rect', 'circle', 'ellipse', 'defs', 'use', 'clipPath'];

    /**
     * Name of the icon to display.
     */
    @Prop({type: String, required: true}) public name!: string;

    /**
     * Set into which the icon belongs (i.e. material, remix, ...).
     */
    @Prop({type: String, default: 'material'}) public set!: string;

    /**
     * Version of the icon, if applicable.
     * If `null`, the first available version will be used if the icon is rendered via local data.
     * Otherwise, the "real" icon component will be in charge of choosing the right version.
     */
    @Prop({type: String, default: null}) public version!: string;

    /**
     * Should the whitespaces around the illustration be removed?
     */
    @Prop({type: Boolean, default: false}) public crop!: string;

    /**
     * Width and height on which to render the icon.
     */
    @Prop({type: String, default: null}) public width!: string|null;
    @Prop({type: String, default: '1em'}) public height!: string|null;

    /**
     * Color to use as fill for the svg.
     */
    @Prop({type: String, default: 'currentColor'}) public color!: string;

    /**
     * An input object describing any number of icons, to store in memory.
     * This object is meant to be generated by the Banquette utility on the documentation website.
     */
    @Prop({type: Object, default: null}) public icons!: [string[], Record<string, any>[]]|null;

    @Computed() public get iconName(): string {
        return `i-${this.set}-${this.name}`;
    }

    @Computed() public get localSetIndex(): number {
        return this.icons !== null ? this.icons[0].indexOf(this.set) : -1;
    }

    /**
     * Check whether the icon is defined globally inside the Vue app.
     * That's our fallback, so if it's not there, we're done.
     */
    @Computed() public get isAmbient(): boolean {
        if (Object.keys(this.$.root.appContext.components).indexOf(this.iconName) > -1) {
            return true;
        }
        if (this.set && this.name) {
            const importCode = `import "@`+`banquette/vue-${this.set}-icons/${this.name}";`;
            console.error(`Icon "${this.name}" of set "${this.set}" doesn\'t exist. You can import it by doing: ${importCode}`);
        }
        return false;
    }

    /**
     * Check if the icon is defined locally, using the `icons` prop.
     */
    @Computed() public get isLocal(): boolean {
        const setIndex = this.localSetIndex;
        if (setIndex < 0) {
            return false;
        }
        return !isUndefined(this.icons![1][setIndex][this.name]);
    }

    /**
     * Try to render the icon's svg.
     */
    @Render() public render(context: any) {
        const btBindTheme = resolveDirective("bt-bind-theme");
        if (this.isLocal) {
            let data = this.icons![1][this.localSetIndex][this.name];
            const version = this.version || Object.keys(data[0])[0];
            data = data[data[0][version]];
            if (data) {
                const createChildren = (children: any[]) => {
                    const output: any[] = [];
                    for (const child of children) {
                        const props: Record<string, string> = {};
                        for (const prop of child[1]) {
                            props[prop[0]] = prop[1];
                        }
                        output.push(h(IconComponent.TagsMap[child[0]], props, createChildren(child[2])));
                    }
                    return output;
                };
                return withDirectives(h('svg', {
                    width: this.width,
                    height: this.height || (!this.width ? '1em' : null),
                    fill: this.color || 'currentColor',
                    viewBox: data[Number(this.crop)]
                }, createChildren(data[2])), [
                    [btBindTheme as any]
                ]);
            }
        }
        if (this.isAmbient) {
            return withDirectives((openBlock(), createBlock(resolveDynamicComponent(this.iconName), mergeProps({
                width: this.width,
                height: this.height,
                color: this.color,
                crop: this.crop,
                class: "bt-icon"
            }, context.$attrs), null, 16 /* FULL_PROPS */)), [
                [resolveDirective("bt-bind-theme") as Directive]
            ]);
        }
        return '?'; // Unknown icon, put a question mark so user can see something.
    }
}
</script>
